pipeline {
    agent any

    environment {
        TAR_PATH = 'C:\\ftp_data\\product_microservice.tar'  // Path where .tar is stored
    }

    stages {
        stage('Clone Repository') {
           steps {
                git branch: 'main', url: 'https://github.com/eldho1markose/product-microservice.git'
                 }  
         }
        stage('Load Docker Image from TAR') {
            steps {
                bat "docker load -i \"${TAR_PATH}\""
            }
        }

        stage('Start Docker Compose') {
            steps {
                bat '''
                docker-compose down -v
                docker-compose up -d
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Image loaded and product microservice started via Docker Compose.'
        }
        failure {
            echo '❌ Something went wrong. Check the logs.'
        }
    }
}
